"""empty message

Revision ID: 04771194b7c0
Revises: f7d5e6c7a8b9
Create Date: 2026-06-04 16:32:43.229598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04771194b7c0'
down_revision = 'f7d5e6c7a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hourly_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_hourly_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_hourly_rates_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_hourly_rates_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_hourly_rates_user_start', ['user_id', 'start_date'], unique=False)

    with op.batch_alter_table('payment_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_adjustments_user_cycle'))

    with op.batch_alter_table('payroll_config', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    
    # Seed existing non-null hourly_rate values from the users table.
    # Uses a far-past start_date so all historical cycles resolve correctly.
    op.execute(
        """
        INSERT INTO user_hourly_rates
            (user_id, org_id, rate, start_date, end_date, created_by, created_at)
        SELECT
            id,
            org_id,
            hourly_rate,
            '2025-04-15',
            NULL,
            'migration:a1b2c3d4e5f6',
            NOW()
        FROM users
        WHERE hourly_rate IS NOT NULL
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_config', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('payment_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_adjustments_user_cycle'), ['user_id', 'cycle_start', 'cycle_end'], unique=False)

    with op.batch_alter_table('user_hourly_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_user_hourly_rates_user_start')
        batch_op.drop_index(batch_op.f('ix_user_hourly_rates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_hourly_rates_org_id'))

    op.drop_table('user_hourly_rates')
    # ### end Alembic commands ###
