"""empty message

Revision ID: 377d99fa2c18
Revises: c6d7e8f9a0b1
Create Date: 2026-06-05 11:45:17.000086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377d99fa2c18'
down_revision = 'c6d7e8f9a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_countries_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_countries_country_id'))

    op.drop_table('checklist_countries')
    with op.batch_alter_table('checklist_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_comment_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_comment_deleted_date'))

    op.drop_table('checklist_comment')
    with op.batch_alter_table('user_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_checklists_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_user_checklists_deleted_date'))
        batch_op.drop_index(batch_op.f('ix_user_checklists_user_id'))

    op.drop_table('user_checklists')
    with op.batch_alter_table('user_checklist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_checklist_item_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_user_checklist_item_deleted_date'))
        batch_op.drop_index(batch_op.f('ix_user_checklist_item_user_id'))

    op.drop_table('user_checklist_item')
    with op.batch_alter_table('team_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_checklists_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_team_checklists_team_id'))

    op.drop_table('team_checklists')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_deleted_date'))

    op.drop_table('checklists')
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_item_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_item_deleted_date'))

    op.drop_table('checklist_item')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mapper_level')
        batch_op.drop_column('checklist_payable_total')
        batch_op.drop_column('assigned_checklists')
        batch_op.drop_column('total_tasks_mapped')
        batch_op.drop_column('overtime_rate')
        batch_op.drop_column('total_checklists_completed')
        batch_op.drop_column('validator_total_checklists_confirmed')
        batch_op.drop_column('overtime_threshold_hours')
        batch_op.drop_column('validator_tasks_validated')
        batch_op.drop_column('total_tasks_invalidated')
        batch_op.drop_column('assigned_projects')
        batch_op.drop_column('validator_tasks_invalidated')
        batch_op.drop_column('total_tasks_validated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tasks_validated', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validator_tasks_invalidated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_projects', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_tasks_invalidated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('validator_tasks_validated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('overtime_threshold_hours', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validator_total_checklists_confirmed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_checklists_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('overtime_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_tasks_mapped', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_checklists', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checklist_payable_total', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mapper_level', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('checklist_item',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('item_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('checklist_item_pkey'))
    )
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_item_deleted_date'), ['deleted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_item_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('checklists',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_payout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('validation_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('active_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('checklists_pkey'))
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_deleted_date'), ['deleted_date'], unique=False)

    op.create_table('team_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('team_checklists_checklist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_checklists_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_checklists_pkey'))
    )
    with op.batch_alter_table('team_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_checklists_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_checklists_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('user_checklist_item',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('item_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_checklist_item_pkey'))
    )
    with op.batch_alter_table('user_checklist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_checklist_item_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_checklist_item_deleted_date'), ['deleted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_checklist_item_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('user_checklists',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_payout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('validation_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('active_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_confirmation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_confirmation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_checklists_pkey'))
    )
    with op.batch_alter_table('user_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_checklists_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_checklists_deleted_date'), ['deleted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_checklists_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('checklist_comment',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('checklist_comment_pkey'))
    )
    with op.batch_alter_table('checklist_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_comment_deleted_date'), ['deleted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_comment_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('checklist_countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('checklist_countries_checklist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('checklist_countries_country_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checklist_countries_pkey'))
    )
    with op.batch_alter_table('checklist_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_countries_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_countries_checklist_id'), ['checklist_id'], unique=False)

    # ### end Alembic commands ###
