"""empty message

Revision ID: 7ae012f39e40
Revises: a7f8a9b0c1d2
Create Date: 2026-06-11 15:26:30.428179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ae012f39e40'
down_revision = 'a7f8a9b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_proposals',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('co_organizers', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_format', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_region', sa.String(length=255), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attendees', sa.Integer(), nullable=False),
    sa.Column('external_orgs', sa.String(length=500), nullable=True),
    sa.Column('expected_outcomes', sa.Text(), nullable=False),
    sa.Column('needs_travel', sa.Boolean(), nullable=False),
    sa.Column('num_travelers', sa.Integer(), nullable=True),
    sa.Column('transport_method', sa.String(length=50), nullable=True),
    sa.Column('origin_city', sa.String(length=255), nullable=True),
    sa.Column('origin_country_id', sa.Integer(), nullable=True),
    sa.Column('destination_city', sa.String(length=255), nullable=True),
    sa.Column('destination_country_id', sa.Integer(), nullable=True),
    sa.Column('estimated_transport_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_travel_expenses', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('budget_categories', sa.Text(), nullable=True),
    sa.Column('budget_amounts', sa.Text(), nullable=True),
    sa.Column('other_expense_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_expense_explanation', sa.Text(), nullable=True),
    sa.Column('cost_justification', sa.Text(), nullable=False),
    sa.Column('agrees_to_report', sa.Boolean(), nullable=False),
    sa.Column('attachment_keys', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_proposals_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_proposals_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_event_proposals_org_status', ['org_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_proposals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_event_proposals_user_submitted', ['user_id', 'submitted_at'], unique=False)

    with op.batch_alter_table('user_name_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name_audits_changed_at'))
        batch_op.drop_index(batch_op.f('ix_user_name_audits_source'))
        batch_op.drop_index(batch_op.f('ix_user_name_audits_user_id'))

    op.drop_table('user_name_audits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_name_audits',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('old_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('old_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('new_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('new_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_name_audits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_name_audits_pkey'))
    )
    with op.batch_alter_table('user_name_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name_audits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_name_audits_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_name_audits_changed_at'), ['changed_at'], unique=False)

    with op.batch_alter_table('event_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_event_proposals_user_submitted')
        batch_op.drop_index(batch_op.f('ix_event_proposals_user_id'))
        batch_op.drop_index('ix_event_proposals_org_status')
        batch_op.drop_index(batch_op.f('ix_event_proposals_org_id'))
        batch_op.drop_index(batch_op.f('ix_event_proposals_country_id'))

    op.drop_table('event_proposals')
    # ### end Alembic commands ###
