"""empty message

Revision ID: 870b5448cbcd
Revises: 377d99fa2c18
Create Date: 2026-06-05 13:49:04.431942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '870b5448cbcd'
down_revision = '377d99fa2c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_analysis_cache_org_id'))

    op.drop_table('element_analysis_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_analysis_cache',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('added', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('modified', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('element_analysis_cache_pkey'))
    )
    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_analysis_cache_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###
