"""rename element_analysis_cache week to day

Revision ID: d88d8b5753e4
Revises: ea65a712a628
Create Date: 2026-05-13 15:03:31.964524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88d8b5753e4'
down_revision = 'ea65a712a628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Date(), nullable=True))
        batch_op.drop_column('week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week', sa.Date(), nullable=True))
        batch_op.drop_column('day')

    # ### end Alembic commands ###
