"""add community and priority to project

Revision ID: f065f913ac66
Revises: 870b5448cbcd
Create Date: 2026-06-08 09:39:12.381027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f065f913ac66'
down_revision = '870b5448cbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('community')

    # ### end Alembic commands ###
