"""drop max_editors and max_validators from project

Revision ID: fa48bec1dfa5
Revises: f065f913ac66
Create Date: 2026-06-08 10:19:51.160554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa48bec1dfa5'
down_revision = 'f065f913ac66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('max_editors')
        batch_op.drop_column('max_validators')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_validators', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_editors', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
